# Generated by Django 4.2.7 on 2023-11-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_dashboard', '0003_initial'),
    ]

    operations = [
    ]
