# Generated by Django 4.2.7 on 2023-11-17 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_dashboard', '0007_project_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
